### ISSUE TITLE
get_children() performance issues

### ISSUE THREAD

**Issue by allan23** [willnorris/wordpress-opengraph#26]
Per the VIP developers site:

**get_children()**
> Similar to get_posts(), but also performs a no-LIMIT query among other bad things by default. Alias of break_my_site_now_please(). Do not use. Instead do a regular WP_Query and make sure that the post_parent you are looking for is not 0 or a falsey value. Also make sure to set a reasonable posts_per_page, get_children will do a -1 query by default, a maximum of 100 should be used (but a smaller value could increase performance)

https://vip.wordpress.com/documentation/caching/uncached-functions/

**Comment by pfefferle** [comment]
thanks for the hint, what do you think about these changes: https://github.com/willnorris/wordpress-opengraph/commit/423c50164d0899a14aa93ebd42bf9ada059c055d ?
