### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by pfefferle** [willnorris/wordpress-opengraph#28]
I would love to add some GitHub Actions, to autoupdate/autodeploy the plugin to WordPress.org. Can you please give me access to the "Secrets" or add your credentials as SVN_USERNAME and SVN_PASSWORD?

**Comment by willnorris** [comment]
I actually don't think there *is* a way to give you access to the secrets on a repo in a personal account like this.  So I've added my wordpress.org svn username and password as secrets.  This seems kinda weird (it'd be much better with an API token or something), but whatevs.
