### ISSUE TITLE
Overriding the meta tag for article:author

### ISSUE THREAD

**Issue by redred** [willnorris/wordpress-opengraph#32]
The plugin renders the following meta tag by default (where "mywebsite" is the domain of the website): 

`<meta property="article:author" name="article:author" content="http://mywebsite/author/admin/" />`

Would it be possible to suppress this tag if I don't want to expose the author URL ("author/admin")? Or, simply override the value `http://mywebsite/author/admin/` with just the domain `http://mywebsite/`?

**Comment by willnorris** [comment]
As noted in the readme, you can hook into the `opengraph_metadata` filter to override any data provided by the plugin.  You'll want to register your function with a higher priority so it runs after the built-in functions and overrides the default values.  So something like:

``` php
add_filter( 'opengraph_metadata', function ($data) {
	$data["article:author"] = "http://mywebsite/";
	return $data;
}, 20);
```

**Comment by redred** [comment]
Thank you. 👍🏼
