### ISSUE TITLE
fediverse account beginning a, c, t or : are trimmed

### ISSUE THREAD

**Issue by aslakr** [willnorris/wordpress-opengraph#36]
It seems like accounts which begins with the letter `a`, `c`, `t` or `:` is trimmed.

E.g. `abc@host.tld` (or `aaabc@host.tld`, `@tactbc@host.tld` etc.) becomes:

```html
<meta content="bc@host.tld" name="fediverse:creator">
```

https://github.com/willnorris/wordpress-opengraph/blob/c710ba7e528cb9521b265b4441636e4013329d32/opengraph.php#L592-L593

`ltrim` https://www.php.net/manual/en/function.ltrim.php might not be useful if you need to remove `acct:`

**Comment by pfefferle** [comment]
hmm, good point! thanks for reporting!
